# Generated by Django 4.2.25 on 2025-10-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
