# Generated by Django 4.2.25 on 2025-10-23 17:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('nota1', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(Decimal('7.0')), django.core.validators.MinValueValidator(Decimal('1.0'))])),
                ('nota2', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(Decimal('7.0')), django.core.validators.MinValueValidator(Decimal('1.0'))])),
                ('nota3', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(Decimal('7.0')), django.core.validators.MinValueValidator(Decimal('1.0'))])),
                ('fecha_ingreso', models.DateField()),
                ('carrera', models.CharField(choices=[('informatica', 'Informatica'), ('administracion', 'Administrador'), ('mecanica', 'Cajero'), ('construccion', 'Construcción'), ('robotica', 'Robotica'), ('contabilidad', 'Contabilidad')], max_length=32)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
